title: Nathan-John Augustyn
lang: af
description: >- # this means to ignore newlines until "baseurl:"
  Data, tegnologie en desentralisasie — idees vir 'n slimmer, meer selfstandige toekoms.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://naugustyn.co.za" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  naugustyn
disqus:
  shortname: your-disqus-shortname

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 5
paginate_path: "/page:num/"
